### ISSUE TITLE
A lot of 404 Overview pages in the Azure DevOps REST API reference

### ISSUE THREAD

**Issue by felixtsem5** [MicrosoftDocs/vsts-rest-api-specs#475]
Example:
From here
https://docs.microsoft.com/en-us/rest/api/azure/devops/pipelines/?view=azure-devops-rest-6.1
then click
Pipeline -> Artifacts / Logs / Pipelines / Runs -> Overview
The only Overview page that works under Pipeline is Preview.
Looks like there are extra `.yaml`s in the URLs.

And this seems to be an issue with the other groups too, I just checked **Permissions Report** and **Operations** and I'm seeing the same thing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0ab71a0-a2df-fa37-83fa-080dece952f6
* Version Independent ID: f74b7d51-aede-ed93-437e-601654d8fa7e
* Content: [Get started with the REST APIs for Azure DevOps Services and Team Foundation Server - Azure DevOps Services REST API](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-6.1)
* Content Source: [index.md](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/index.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by pazand** [comment]
Hi @felixtsem5 , thanks for raising the issue. Just wanted to acknowledge this; a fix should be out shortly.

Thanks,
Parsa Zand

**Comment by felixtsem5** [comment]
@pazand - it looks like the overview pages of the first levels are fixed (Pipelines -> Overview), but the second level overview pages haven't been yet (For example, Pipelines -> Pipelines -> Overview).

**Comment by parsamzand** [comment]
@felixtsem5 Yes that will be fixed as well. Thanks!

**Comment by pazand** [comment]
@felixtsem5 Yes that will be fixed as well. Thanks!

**Comment by boblechat** [comment]
July 2nd, and the documentation is still broken.
I'm starting to miss the old MSDN Library shipped on DVD...

**Comment by kamalhabieb** [comment]
This issue has been fixed.
